### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by ghost** [djacu/nixos-dotfiles-work#5]
* Why have a `mountpoint` for zpool and bpool that are anything but none especially when `canmount=off`?
 * This is not my decision, but rlaager's: [see here](https://github.com/openzfs/openzfs-docs/pull/139)
* What does this line do (`mount -o bind /mnt/state/$i /mnt/$i`)? Or more specifically, what is its intention?
  * From the `mount` man page, it says, "Remount part of the file hierarchy somewhere else.". So it appears that this is a way to store system mutable state in a separate `state` dataset that is not reproducible by NixOS.
  * This is the correct interpretation.
* In the Overview - Dataset layout, the container field for Dataset `rpool/sys/ROOT`, says "contains boot environment". Should that be "contains ***root*** environment"?
 * No. "boot environment" is a term inherited from Solaris, referring to an instance of a bootable system: rpool/.../default plus bpool/.../default.  It's of little importance for NixOS as the system state is managed by Nix, but for traditional distros, it's of great importance and is the fundamental design concept underlying bieaz.

**Comment by djacu** [comment]
Thanks for the comments!

> * This is not my decision, but rlaager's: [see here](https://github.com/openzfs/openzfs-docs/pull/139)

I read through rlaager's suggestions but

> This should remain mountpoint=/boot. It's less important than the root pool having a mountpoint of /, but it's there for fundamentally the same reason (custom datasets).

is pretty cryptic. I suppose if you were to manually create a dataset on `rpool` or `bpool` in the future, it is handy that it has a defined `mountpoint`. I'm not sure what situation requires these "custom datasets" but maybe I'll learn that in time.

**Comment by ghost** [comment]
Hi!  I've updated the guide to use native Nix expressions to handle both single disk and multi disk setups for both legacy BIOS boot and UEFI boot.  You can checkout the latest guide [here](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS/1-preparation.html)!  It is much cleaner than before, and, in my test I could complete an installation under 8 minutes, from booting the live media to reboot to the new system.

**Comment by ghost** [comment]
I've uploaded the complete configuration of my laptop at [this repo](https://github.com/ne9z/dotfiles-nixos), in which the details of immutable root and user home is documented.
